name: CI JS Tests

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Clean Install
          run: npm ci

        - name: Install dependencies
          run: | 
            npm install
            npx husky install
            chmod -R u+x .husky

        - name: Run tests
          run: npm test
